apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    k8s-app: test
    foo: bar
  name: test-deploy
spec:
  replicas: 2  # This is the replicas field
  selector:
    matchLabels:
      k8s-app: test
  template:  # The template key
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: "test"  # This is a pod label
    spec:
      containers:
      - name: test-container
        image: nginx:1.17  # The image value has a colon
        command:
        - "/bin/sh"
        args:
        - -c  #+workload:certManagerResourceName:default="cert-manager":type=string
        - while true; do ls; sleep 10; done  # second value in array
        securityContext:
          allowPrivilegeEscalation: false  # Here is a bool value

